/**
 * English strings: every user-visible string, plus the identity prose.
 *
 * What gets translated is decided by the **type, not the role**. Prose - body copy, page
 * intros, placeholders, an empty or error explanation, the identity text - is translated.
 * Anything set as micro-type stays English: labels, filters, counters, stat labels,
 * readouts, serials, page eyebrows, brand and technology names. It is notation, part of the
 * instrument look rather than reading matter, and a translated label reads as a machine
 * translation. See `docs/CONVENTIONS.md` for the two cases that look like exceptions.
 *
 * `Strings` is derived from this object, so adding a key here immediately requires it in
 * every other locale, with no third place to keep in sync.
 */

export const en = {
  common: {
    skipToContent: 'Skip to content',
    close: 'Close',
    all: 'ALL',
    loading: 'LOADING',
    pleaseWait: 'PLEASE WAIT',
    /* `MIN` read as a relative timestamp beside the age in a listing, so the unit is spelled out. */
    minRead: 'MIN READ',
  },

  /* The button shows the locale you are reading; the action is announced in it. */
  locale: {
    short: 'EN',
    switchTo: 'Switch to Chinese',
  },

  nav: {
    label: 'Navigation',
    /* Screen-reader names for the three navigation regions. */
    primary: 'Main',
    drawer: 'Mobile',
    footer: 'Footer',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    search: 'Search',
    toggleDark: 'Switch to dark mode',
    toggleLight: 'Switch to light mode',
    links: 'Links',
    sitemap: 'Sitemap',
  },

  /*
   * Page names, keyed by `site.nav[].key`. The navigation, the page `<h1>`s and the route
   * titles all read from here, so a page cannot be renamed in one place and not in another.
   */
  pages: {
    home: 'Home',
    projects: 'Projects',
    about: 'About',
    blog: 'Notes',
    contact: 'Contact',
  },

  /* Labels for site.socials, keyed by the entry's `key`. Brand names stay. */
  socials: {
    github: 'GitHub',
    bilibili: 'Bilibili',
    afdian: 'Afdian',
    /* Hyphenated to match the width of the other three chips in the row; both forms are
       correct. Rendered upper-case by `SocialLinks`, so it reaches the screen as E-MAIL. */
    email: 'E-mail',
  },

  cover: {
    coord: 'Coord',
    local: 'Local',
    base: 'Base',
    focus: 'Focus',
    status: 'Status',
    /** Base / Focus / Status values. Notation stays English; words translate. */
    baseValue: 'CN / REMOTE',
    focusValue: 'NECOKARA',
    /*
     * Deliberately the longest of the three: the cells are right-aligned, so a longer
     * value only pushes its own left edge out.
     */
    statusValue: 'OPEN / HEALTHY',
    since: 'EST.',
    /** Primary call to action. */
    enter: 'Enter',
    /* A plain declarative sentence, not a slogan. */
    note: 'My projects and notes are here.',
    /*
     * The wordmark typed by the typewriter, as [line 1, line 2] pairs; the loop cycles
     * through them. Deliberately has no locale override - it is a layout element tuned for
     * Latin capitals.
     */
    phrases: [
      ['CHROLLIS', 'GITHUB.IO.'],
      ['CODING', 'EVERYDAY.'],
    ] as [string, string][],
  },

  projects: {
    /** Eyebrow. Stays as-is in every locale - see the note at the top. */
    subtitle: 'PROJECTS',
    intro: 'Repositories from GitHub. Expand a card for its README.',
    total: 'TOTAL',
    stars: 'STARS',
    forks: 'FORKS',
    filter: 'FILTER',
    items: 'ITEMS',
    empty: 'NOTHING IN THIS CATEGORY',
    moreOnGithub: 'MORE ON',
    code: 'CODE',
    showReadme: 'Readme',
    hideReadme: 'Hide readme',
    readmeLoading: 'Fetching readme...',
    readmeMissing: 'This repo has no README.',
    noDescription: 'No description yet.',
    active: 'ACTIVE',
    archived: 'ARCHIVED',
    languages: 'LANGUAGES',
    snapshot: 'SNAPSHOT',
  },

  about: {
    subtitle: 'ABOUT',
    selfIntro: 'INTRO',
    /* Facts panel */
    factLocation: 'LOCATION',
    factEmail: 'E-MAIL',
    /* Statistics panel */
    stats: 'Statistics',
    statsByVolume: 'BY CODE VOLUME',
    /*
     * Statistic labels are not translated and so are not mapped here: they arrive as
     * English strings scraped from the SVG generated by Chrollis/github-stats-chrollis,
     * and they are readout labels rather than prose.
     */
  },

  blog: {
    subtitle: 'NOTES',
    intro: 'My notes and fiction are here.',
    tags: 'TAGS',
    empty: '0 POSTS',
    /* Reader-facing: says the list is empty, not how to add a post. */
    emptyHint: 'Nothing published yet.',
    backToNotes: 'BACK TO NOTES',
    newer: 'Newer post',
    older: 'Older post',
    notFound: 'Post not found',
    postNav: 'Post navigation',
  },

  contact: {
    subtitle: 'CONTACT',
    intro:
      'For anything about a project, please open an issue on its repository. For anything else, please use one of the channels below.',
    social: 'SOCIAL',
    name: 'NAME',
    email: 'E-MAIL',
    subject: 'SUBJECT',
    message: 'MESSAGE',
    /*
     * Placeholders are English in both locales on purpose, so this locale is their only
     * home and `zh` carries no override for them.
     *
     * They are examples and invitations rather than reading matter - the same class as the
     * labels above them, which are English everywhere for the same reason. And they are the
     * one string the locale flip cannot animate: `Scramble` writes a text node, a
     * placeholder is an attribute, so a translated placeholder snapped to the new language
     * in the middle of a page turning over character by character. A hint that changes
     * language is worth less than a hint that does not. See `docs/CONVENTIONS.md`.
     */
    namePlaceholder: 'What should I call you?',
    /* Capitalised like its siblings above and below: an example address is an example
       string, and a lone lowercase start read as a typo in the column. */
    emailPlaceholder: 'Example@example.com',
    subjectPlaceholder: 'What is this about?',
    messagePlaceholder: 'Write your message here...',
    send: 'Send message',
    sending: 'Sending',
    privacy: 'Used only to reply. Never published.',
    sent: 'Message sent. I will get back to you soon.',
    sendFailed: 'Send failed',
    sendFailedHint: 'Please try again later, or reach me on GitHub instead.',
    /*
     * Field errors and the form summary, as READOUTS rather than sentences: the label above
     * the field already says which field it is, and what a field needs is a state, not an
     * explanation. English in both locales, like those labels and the status line - see the
     * note on placeholders above and `docs/CONVENTIONS.md`.
     *
     * `emailUnusable` is separate from `emailIncompleteDomain` so neither has to lie: the
     * first is an address that cannot be an address at all (whitespace or a comma in the
     * local part, two `@`, longer than a DNS name), the second is one that is simply not
     * finished. See `src/lib/validate.ts` for the rules themselves.
     */
    required: 'REQUIRED',
    emailMissingAt: 'MISSING "@"',
    emailIncompleteDomain: 'INCOMPLETE DOMAIN',
    emailUnusable: 'CHECK THE ADDRESS',
    formIncomplete: 'FORM INCOMPLETE',
    /*
     * Marks the one field that is NOT required, rather than asterisking the three that are:
     * the exception is the useful information, and three marks on four fields is noise. It
     * lives inside the field's `<label>`, so a screen reader reads "SUBJECT OPTIONAL" as the
     * field's name - the exception is worth announcing.
     */
    optional: 'OPTIONAL',
    /*
     * The authorization beat, read out as states rather than explained: the track is a
     * slider, so what it wants is legible, and a sentence above it would read as a caption
     * under an exhibit. `authRequired` is the one line the form itself repeats, because a
     * submit that goes nowhere has to say why.
     */
    auth: 'AUTH',
    authHold: 'HOLD',
    authSampling: 'SAMPLING',
    authTrace: 'TRACE',
    authOk: 'OK',
    authShort: 'SHORT',
    authNoise: 'NOISE / RETRY',
    authRequired: 'AUTH REQUIRED',
    notConfigured: 'NOT CONFIGURED',
    notConfiguredHelp: 'The form is not available right now. Please use email instead.',
    emailMe: 'E-mail me',
    feedNote: 'Prefer a reader? Subscribe by',
    learnAboutMe: 'More about me',
    formProviderWeb3: 'WEB3FORMS',
    formProviderFormSubmit: 'FORMSUBMIT',
  },

  search: {
    title: 'Search',
    close: 'Close search',
    placeholder: 'Search titles, tags and body text...',
    inputLabel: 'Search keyword',
    hint: 'Type to search',
    hintCount: 'posts indexed',
    noMatch: 'NO MATCH FOR',
    keys: 'Up/Down to select - Enter to open - Esc to close',
    engine: 'FLEXSEARCH / LOCAL INDEX',
  },

  comments: {
    label: 'Comments',
    poweredBy: 'POWERED BY GISCUS',
    loading: 'Loading comments...',
  },

  notFound: {
    label: 'ERROR / PAGE NOT FOUND',
    body: 'Nothing at this address. The link may be stale, or the page was never here.',
    home: 'Back to home',
    suggestions: 'You might be looking for',
  },

  footer: {
    meta: 'Files',
    builtWith: 'BUILT WITH REACT - VITE - DEPLOYED ON GITHUB PAGES',
  },

  /* The crash screen a visitor sees when the app fails to render. */
  crash: {
    label: 'Runtime error',
    title: 'Something broke.',
    body: 'The page failed to render. Reloading usually clears it. If it keeps happening, the browser console has the details.',
    reload: 'Reload',
  },

  /* The boot overlay. Serial numbers stay; the words translate. */
  boot: {
    label: 'Initializing',
    serial: 'SYS.001',
    status: 'Loading core assets',
    statusSerial: 'SYS.001 / BOOT',
    skip: 'CLICK TO SKIP',
  },

  /* One description per route, for search results and link previews. `{count}` is filled
     by the caller. */
  meta: {
    site: 'Personal homepage of Chrollis.',
    projects: 'Repositories from GitHub.',
    about: 'Background and statistics.',
    blog: 'Notes and fiction. {count} posts so far.',
    contact: 'Ways to get in touch.',
    notFound: 'Page not found.',
  },

  /* Machine-readable files, listed in the footer and on the contact page. */
  files: {
    rss: 'RSS',
    sitemap: 'SITEMAP',
    robots: 'ROBOTS',
  },

  /* Identity prose. */
  content: {
    /** Short line under the cover wordmark and in the footer; uppercased there. */
    role: 'Building Necokara',
    /** About page body, one string per paragraph. */
    bio: [
      "I'm probably not built for the kind of life where every day is packed full. I listen a bit, do a bit, game when I'm tired, sleep when I'm sleepy.",
      "Being around people is genuinely exhausting. Half the time someone says something and I turn it over twice in my head and still don't know how to respond, so eventually I stopped making the first move - and I can't tell if it's my problem, or there just isn't much to say.",
      "But what I've committed to, I don't blur on. Everything else can be as loose as it wants; the one thing I've settled with myself cannot.",
    ] as string[],
    /* Footer blurb. Not a description of the site's contents. */
    description: 'I write code because it is fun. I hope it still is when it becomes a job.',
    location: 'Sichuan, China',
    keywords: ['Chrollis', 'C++', 'Qt', 'Tauri', 'Win32', 'necokara'],
  },
}

/** Every user-visible string on the site. Derived from the English object. */
export type Strings = typeof en

/**
 * Recursive partial, with arrays as leaves: a translation replaces `bio` and `keywords`
 * wholesale, because a positional merge of differing lengths is nonsense.
 *
 * The array branch has to come first, or `Object`'s index signature swallows arrays and
 * every element becomes optional - a translation could ship a two-paragraph bio.
 */
export type DeepPartial<T> = T extends readonly unknown[]
  ? T
  : T extends object
    ? { [K in keyof T]?: DeepPartial<T[K]> }
    : T
