/*
 * Brand icon generator (`npm run icons`, also run before `dev` and `build`).
 *
 * It draws nothing: every path comes from `src/data/brand.ts`, the same source
 * `LogoMark.tsx` renders. The job is only to wrap that geometry in the documents that
 * have to exist as files, because the browser fetches them directly.
 *
 * Output is committed into `public/brand/` so the dev server serves it and no build is
 * needed to preview; every run overwrites, so edit `brand.ts` instead.
 *
 * `og.svg` is the exception - nothing fetches it, so it goes to `.cache/`. iOS ignores an
 * SVG touch icon and crawlers do not render an SVG `og:image`, hence the PNGs.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { Resvg } from '@resvg/resvg-js'

import { BRAND, MARK_INSET_VIEW_BOX, MARK_PATH, MARK_VIEW_BOX } from '../src/data/brand.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const publicDir = join(root, 'public')
/* Served: fetched directly by URL, so it has to exist as a real file. */
const brandDir = join(publicDir, 'brand')
/* Not served: `og.svg` is only the source `og.png` is rendered from. */
const cacheDir = join(root, '.cache', 'brand')

const BANNER = [
  'Generated by scripts/build-icons.mjs from src/data/brand.ts.',
  'Do not edit this file: run `npm run icons` after changing that module.',
].join(' ')

/*
 * How much of the viewBox the mark fills in a maskable icon. Android only guarantees the
 * middle 80% (a circle of radius 25.6 in a 64 box); the monogram's half-diagonal is 25.5
 * at full size, which is not a margin.
 */
const MASKABLE_SCALE = 0.55

/** Scale a group about the centre of the viewBox rather than the origin. */
const scaledAboutCentre = (scale) => `translate(32 32) scale(${scale}) translate(-32 -32)`

/* ------------------------------------------------------------------ */
/* favicon.svg                                                         */
/* ------------------------------------------------------------------ */

/* The favicon follows the browser chrome, not the site theme: it cannot read the page's
   state, so it answers the OS preference - near-black on a light tab bar, white on dark. */
const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${MARK_INSET_VIEW_BOX}">
  <!-- ${BANNER} -->
  <style>
    .mark { fill: ${BRAND.background} }
    @media (prefers-color-scheme: dark) { .mark { fill: ${BRAND.onDark} } }
  </style>
  <path class="mark" d="${MARK_PATH}"/>
</svg>
`

/* ------------------------------------------------------------------ */
/* icon-maskable.svg                                                   */
/* ------------------------------------------------------------------ */

/* Opaque plate: a maskable icon is composited over an unknown launcher background. */
const maskable = `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="${MARK_VIEW_BOX}">
  <!-- ${BANNER} -->
  <rect width="64" height="64" fill="${BRAND.background}"/>
  <g transform="${scaledAboutCentre(MASKABLE_SCALE)}">
    <path d="${MARK_PATH}" fill="${BRAND.onDark}"/>
  </g>
</svg>
`

/* ------------------------------------------------------------------ */
/* og.svg                                                              */
/* ------------------------------------------------------------------ */

const OG_WIDTH = 1200
const OG_HEIGHT = 630
const OG_STEP = 40

/** The background grid the site uses behind its own sections, at the same pitch. */
function gridLines() {
  const lines = []
  for (let x = OG_STEP; x < OG_WIDTH; x += OG_STEP) {
    lines.push(`<path d="M${x} 0V${OG_HEIGHT}"/>`)
  }
  for (let y = OG_STEP; y < OG_HEIGHT; y += OG_STEP) {
    lines.push(`<path d="M0 ${y}H${OG_WIDTH}"/>`)
  }
  return `<g stroke="${BRAND.grid}" stroke-width="1" fill="none">${lines.join('')}</g>`
}

/* Pure geometry, no text: type would mean embedding a font, and the wordmark is already
   carried by `og:title`. The yellow ticks match `.ak-corners`. */
const openGraph = `<svg xmlns="http://www.w3.org/2000/svg" width="${OG_WIDTH}" height="${OG_HEIGHT}" viewBox="0 0 ${OG_WIDTH} ${OG_HEIGHT}">
  <!-- ${BANNER} -->
  <rect width="${OG_WIDTH}" height="${OG_HEIGHT}" fill="${BRAND.background}"/>
  ${gridLines()}
  <rect x="48" y="48" width="${OG_WIDTH - 96}" height="${OG_HEIGHT - 96}" fill="none" stroke="${BRAND.border}" stroke-width="2"/>
  <path d="M48 128V48h80" fill="none" stroke="${BRAND.accent}" stroke-width="4"/>
  <path d="M${OG_WIDTH - 48} ${OG_HEIGHT - 128}v80h-80" fill="none" stroke="${BRAND.accent}" stroke-width="4"/>
  <g transform="translate(${OG_WIDTH / 2} ${OG_HEIGHT / 2}) scale(2) translate(-32 -32)">
    <path d="${MARK_PATH}" fill="${BRAND.onDark}"/>
  </g>
</svg>
`

/*
 * PNG. Two slots cannot use an SVG: iOS ignores an SVG `apple-touch-icon`, and crawlers
 * do not render an SVG `og:image`. Both are rendered from the *same strings* written to
 * disk, so raster and vector are one artwork by construction - two drawings of one logo
 * is the failure mode `src/data/brand.ts` exists to prevent.
 *
 * The rasteriser is `@resvg/resvg-js`, a prebuilt Rust binary: two packages, no compiler,
 * and a devDependency so it stays out of the bundle. `sharp` was tried and rejected - its
 * libvips build has no librsvg, so it produced a valid PNG of nothing but the background.
 *
 * The maskable icon uses the inset frame: at icon sizes the mark needs the breathing room
 * the tight authored viewBox does not have.
 */
async function renderPng(svg, width) {
  const resvg = new Resvg(svg, {
    fitTo: { mode: 'width', value: width },
    /* Flat colour on flat background: keep the mark's corners crisp, not over-antialiased. */
    shapeRendering: 2,
    logLevel: 'error',
  })
  return resvg.render().asPng()
}

/*
 * apple-touch-icon is 180px, the size current iOS devices actually request, not the
 * authored 512. The manifest gets the maskable raster at 512 as well as the SVG, because
 * some Android launchers ignore an SVG entry and fall back to a letter tile.
 */
const rasterOutputs = [
  ['apple-touch-icon.png', maskable, 180],
  ['icon-maskable.png', maskable, 512],
  ['og.png', openGraph, OG_WIDTH],
]

/* ------------------------------------------------------------------ */

const outputs = [
  ['favicon.svg', favicon],
  ['icon-maskable.svg', maskable],
]

mkdirSync(brandDir, { recursive: true })

for (const [name, contents] of outputs) {
  writeFileSync(join(brandDir, name), contents, 'utf8')
  console.log(`[icons] public/brand/${name}  ${contents.length} bytes`)
}

for (const [name, svg, width] of rasterOutputs) {
  const png = await renderPng(svg, width)
  writeFileSync(join(brandDir, name), png)
  console.log(`[icons] public/brand/${name}  ${png.length} bytes  ${width}px wide`)
}

/* Generated every run but never shipped: useful to inspect when the raster is wrong, and
   a 1.8KB file nothing fetched back when it lived in `public/`. */
mkdirSync(cacheDir, { recursive: true })
writeFileSync(join(cacheDir, 'og.svg'), openGraph, 'utf8')
console.log(`[icons] .cache/brand/og.svg  ${openGraph.length} bytes  (not served)`)

/*
 * `og:image:width`/`height` is written by hand in `src/lib/seo.ts`, because that module
 * runs in the browser and cannot read these constants. A duplicated fact waiting to
 * drift, so it is checked: read the PNG's own IHDR back and fail if the two disagree. A
 * wrong size does not break the image, it quietly changes how crawlers lay out the card.
 */
const og = readFileSync(join(brandDir, 'og.png'))
const ogWidth = og.readUInt32BE(16)
const ogHeight = og.readUInt32BE(20)
const seo = readFileSync(join(root, 'src/lib/seo.ts'), 'utf8')
const declared = /OG_IMAGE = \{ width: (\d+), height: (\d+) \}/.exec(seo)
if (!declared) {
  throw new Error('[icons] could not find OG_IMAGE in src/lib/seo.ts')
}
if (Number(declared[1]) !== ogWidth || Number(declared[2]) !== ogHeight) {
  throw new Error(
    `[icons] og.png is ${ogWidth}x${ogHeight} but src/lib/seo.ts declares ` +
      `${declared[1]}x${declared[2]}. Update OG_IMAGE there.`,
  )
}
console.log(`[icons] og.png size matches the og:image tags (${ogWidth}x${ogHeight})`)
